name: hexo-auto-deploy

on: 
  push:
    branches:
      -hexo

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean
      uses: bookshiyi/action-hexo@master
      with:
        args: clean
    - name: Generate
      uses: bookshiyi/action-hexo@master
      with:
        args: generate
    - name: Deploy
      uses: bookshiyi/action-hexo@master
      env:
        EMAIL: ibookshiyi@gmail.com
        NAME: bookshiyi
      with:
        args: deploy
